on:
  create:
    tags:
      - v*
jobs:
  test_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: echo ${{ github.event_name == 'create' && startsWith(github.event.ref, 'v') }}
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event.ref }}
      - uses: casperdcl/deploy-pypi@v2
        with:
          password: ${{ secrets.TEST_PYPI }}
          requirements: twine wheel
          pip: wheel -w dist/ --no-deps .
          # only upload if a tag is pushed (otherwise just build & check)
          upload: ${{ github.event_name == 'create' && startsWith(github.event.ref, 'v') }}
          url: https://test.pypi.org/legacy/
